<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_ProductEnquiry
 * @copyright   Copyright (c) 2025 M2Commerce
 * @author      dawood
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use M2Commerce\ProductEnquiry\Block\Form;

/** @var Form $block */
/** @var Escaper $escaper */
?>

<script>
    function productEnquiryForm() {
        return {
            productEnquiryButtonDisabled: false,
            async submitForm(event) {
                event.preventDefault(); // Prevent default submit
                this.productEnquiryButtonDisabled = true;
                document.getElementById('productenquiry-submit-btn').classList.add('loading');


                const form = event.target;
                const formData = new FormData(form);
                const actionUrl = form.action;

                try {
                    const response = await fetch(actionUrl, {
                        method: 'POST',
                        body: formData,
                    });

                    const result = await response.json();

                    window.dispatchMessages([{
                        type: result.result ? 'success' : 'error',
                        text: result.result
                            ? '<?= $escaper->escapeHtml(__("Thank you for submitting your request.")); ?>'
                            : '<?= $escaper->escapeHtml(__("An error occurred - your request was not sent.")); ?>'
                    }]);

                    if (result.result) {
                        form.reset();
                    }
                } catch (error) {
                    window.dispatchMessages([{
                        type: 'error',
                        text: '<?= $escaper->escapeHtml(__("An error occurred - your request was not sent.")); ?>'
                    }]);
                }
                document.getElementById('productenquiry-submit-btn').classList.remove('loading');
                this.productEnquiryButtonDisabled = false;
            }
        };
    }
</script>

<div class="product-enq-main">
    <span class="title-sm font-medium">
        <?= $escaper->escapeHtml(__("Please tell us the name of product you couldn't find in here")); ?>
    </span>

    <div data-bind="scope: 'messages'">
        <div class="messages" data-bind="visible: messageList().length">
            <div role="alert" class="message" data-bind="foreach: { data: messageList, as: 'message' }">
                <div data-bind="css: message.type, text: message.text"></div>
            </div>
        </div>
    </div>

    <form name="productenquiryform"
          method="post"
          action="<?= $escaper->escapeUrl($block->getUrl('productenquiry/index/index')) ?>"
          x-data="productEnquiryForm()"
          @submit="submitForm">

        <div class="Product-Sb-btn">
            <label class="normal-input text-sm" for="comment">
                <?= $escaper->escapeHtml(__("I was looking for")); ?>
            </label>
            <div class="control text-sm mt-5">
                <input placeholder="Product name"
                       name="comment"
                       id="comment"
                       title="<?= $escaper->escapeHtml(__('Comment')) ?>"
                       class="form-input w-full"
                       type="text"
                       required>

                <button id="productenquiry-submit-btn"
                        class="btn btn-secondary w-full mt-5"
                        type="submit"
                        :disabled="productEnquiryButtonDisabled">
                    <span><?= $escaper->escapeHtml(__('Contact Us')) ?></span>
                    <span class="loader" style="display:none;"></span>
                </button>
            </div>
        </div>
    </form>
</div>
